# Имя workflow, которое будет отображаться в интерфейсе GitHub Actions
name: UI tests

# Указываем триггеры запуска данного workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Джоба для запуска автотестов
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Check out repository
        uses: actions/checkout@v6

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      # 4. Запускаем тесты и генерируем allure-results
      - name: Run Playwright tests with pytest and generate Allure results
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses 2

      # 5. Восстанавливаем историю покрытия из кеша
      - name: Restore Coverage history
        uses: actions/cache/restore@v5
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}
          restore-keys: |
            coverage-history-

      # 6. Генерируем HTML-отчет покрытия и обновляем историю
      - name: Generate Coverage report
        run: |
          ui-coverage-tool save-report

      # 7. Сохраняем историю покрытия обратно в кэш
      - name: Cache Coverage  history
        if: always()
        uses: actions/cache/save@v5
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}

      # 8. Загружаем HTML-отчет покрытия как артефакт
      - name: Upload Coverage report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage.html

      # 9. Сохраняем allure-results как артефакт
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: allure-results
          path: allure-results

  # Джоба для публикации отчета
  publish-report:
    runs-on: ubuntu-latest

    # Запускается только после успешного завершения run-tests
    needs: run-tests

    steps:
      # 1. Клонируем репозиторий
      - name: Check out repository
        uses: actions/checkout@v6

      # 2. Загружаем allure-results из артефактов
      - name: Download Allure results
        uses: actions/download-artifact@v8
        with:
          name: allure-results
          path: allure-results

      # 3. Получаем историю Allure отчетов, если она существует
      - name: Get Allure history
        uses: actions/checkout@v6
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 4. Генерируем Allure отчет с историей
      - name: Generates Allure Report with history
        uses: simple-elf/allure-report-action@v1.14
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      # 5. Публикуем отчет на GitHub Pages
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
